name: 'GitHub Actions Email Bot'

on:
  push:
  pull_request:

jobs:
  emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: get commit message
        run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event }})

      - name: show commit message
        run: echo $commitmsg > test.txt

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Action Email Test
          body: file://test.txt
          to: hawu6155@colorado.edu
          from: GitHub Actions
          content_type: text/plain