name: 'GitHub Actions Email Bot'

on:
  push:
  pull_request:

jobs:
  emailbot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: GITHUB CONTEXT
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_CONTEXT" > test.json
          
      - name: Generate info
        run: |
          sha=`jq '.sha' test.json`
          email=`jq '.event.head_commit.author.email' test.json`
          echo ${sha:0:8} > test.txt
          echo $email >> test.txt
          echo "::set-env name=EMAIL::$email"

      - name: Test
        run: |
          echo $EMAIL

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: wuhao960123@gmail.com
          password: jdfltlenenhbfqnt
          subject: Github Action Email Test
          body: file://test.txt
          to: boxu@google.com
          from: GitHub Actions
          content_type: text/plain