name: 'GitHub Actions Email Bot'

on:
  push:
  pull_request:

jobs:
  emailbot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: GITHUB CONTEXT
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT" > test.json
    
      - name: get commit message
        run: |
          echo ::set-env name=email::$(git log --format=%B -n 1 ${{ github.event.commits.author.email }})

      - name: show commit message
        run: |
          echo $email > test.txt

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Action Email Test
          body: file://test.json
          to: hawu6155@colorado.edu
          from: GitHub Actions
          content_type: text/plain