name: 'GitHub Actions Email Bot'

on:
  push:
  pull_request:

jobs:
  emailbot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: GITHUB CONTEXT
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
      - name: Generate info
        run: |
          echo ::set-env name=SHA::$(git log --format=%h -n 1)
          echo ::set-env name=EMAIL::$(git log --format=%ae -n 1)
          echo ::set-env name=test::$(git log --format=%ae -n 5)

      - name: Test
        run: |
          echo $EMAIL
          echo $SHA
          echo $test

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: wuhao960123@gmail.com
          password: jdfltlenenhbfqnt
          subject: Github Action Email Test
          body: ${{ env.SHA }}
          to: ${{ env.EMAIL }}
          from: GitHub Actions
          content_type: text/plain